services:
  mongodb:
    image: mongo:7.0
    container_name: node-api-mongodb

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
